# Generated by Django 4.1 on 2025-04-10 16:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fitnessactivity",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="fitnessactivity",
            name="intensity",
        ),
        migrations.RemoveField(
            model_name="fitnessactivity",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="student",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="student",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="teacherchallenge",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="teacherchallenge",
            name="points_reward",
        ),
        migrations.RemoveField(
            model_name="teacherchallenge",
            name="target_type",
        ),
        migrations.RemoveField(
            model_name="team",
            name="color",
        ),
        migrations.RemoveField(
            model_name="team",
            name="total_points",
        ),
        migrations.AddField(
            model_name="fitnessactivity",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="fitnessactivity",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacherchallenge",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="fitnessactivity",
            name="activity_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="fitnessactivity",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fitness.student"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fitness.team"
            ),
        ),
        migrations.AlterField(
            model_name="teacherchallenge",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
