# Generated by Django 4.1 on 2025-04-10 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0003_housepoints"),
    ]

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("mascot", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="house",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fitness.house",
            ),
        ),
    ]
