# Generated by Django 4.1 on 2025-04-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0004_house_student_house"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
