# Generated by Django 4.1 on 2025-04-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0005_house_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="confetti_shown",
            field=models.BooleanField(default=False),
        ),
    ]
