# Generated by Django 4.1 on 2025-04-21 20:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0008_userprofile_recommendationlog_acceptedchallenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessactivity",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="house",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fitness.house",
            ),
        ),
    ]
