# Generated by Django 4.1 on 2025-04-26 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fitness", "0010_house_description_house_theme_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fitnessactivity",
            name="student",
        ),
        migrations.AlterField(
            model_name="fitnessactivity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
