# Generated by Django 4.1 on 2025-04-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0011_remove_fitnessactivity_student_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="housechallenge",
            name="canonical_activity",
            field=models.CharField(
                blank=True,
                help_text="Normalized activity type for robust matching (e.g. 'walk', 'yoga')",
                max_length=50,
                null=True,
            ),
        ),
    ]
