# Generated by Django 4.1 on 2025-04-28 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0012_housechallenge_canonical_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_tip_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_tip_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="acceptedchallenge",
            name="accepted_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="acceptedchallenge",
            name="challenge_description",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="acceptedchallenge",
            name="completed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="fitnessactivity",
            name="activity_type",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="fitnessactivity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="fitnessactivity",
            name="date",
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="userbadge",
            name="earned_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
