# Generated by Django 4.1 on 2025-04-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fitness",
            "0013_userprofile_last_tip_date_userprofile_last_tip_text_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_answers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_complete",
            field=models.BooleanField(default=False),
        ),
    ]
