# Generated by Django 4.1 on 2025-04-28 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fitness", "0016_team_created_at_team_created_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Emoji or icon name", max_length=100
                    ),
                ),
                (
                    "unlock_points",
                    models.PositiveIntegerField(
                        default=0, help_text="Points needed to unlock"
                    ),
                ),
                (
                    "unlock_streak",
                    models.PositiveIntegerField(
                        default=0, help_text="Streak needed to unlock"
                    ),
                ),
                (
                    "unlock_challenges",
                    models.PositiveIntegerField(
                        default=0, help_text="Challenges completed to unlock"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fitness.reward"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "reward")},
            },
        ),
    ]
