# Generated by Django 4.1 on 2025-04-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0017_reward_userreward"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bot_persona",
            field=models.CharField(
                choices=[
                    ("arnold", "Classic Arnold"),
                    ("jennifer", "Jennifer Aniston"),
                    ("katy", "Katy Perry"),
                    ("mel", "Mel Gibson"),
                ],
                default="arnold",
                max_length=20,
            ),
        ),
    ]
