# Generated by Django 4.1 on 2025-04-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0019_challengesuggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="first_activity_logged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="has_seen_onboarding",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="house_joined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_challenge_prompted",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_octocoach_message",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_points_milestone",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_streak_milestone",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
